### ISSUE TITLE
Release on maven central

### ISSUE THREAD

**Issue by marcospassos** [julianthome/inmemantlr#1]
Is there any reason for it to not to be released on maven central? This plugin is very relevant and useful.

**Comment by julianthome** [comment]
Dear Marcos,

thanks for your Feedback. Sure, I will make it available on Maven Central. 

Best wishes and kind regards,
  Julian

**Comment by julianthome** [comment]
Dear Marcos,

sorry for the late reply, I just published the first release on https://oss.sonatype.org/content/groups/public/com/github/julianthome/inmemantlr/1.0/.

Best,
  Julian
