### ISSUE TITLE
tree

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#12]
Hi, possible to generate the tree of the rules? I am developing antlr plugin for netbeans.
![antlrdt-v4-plugin](https://user-images.githubusercontent.com/1779905/28753049-04c288ce-7560-11e7-848f-10d9edc1fd03.png)

**Comment by julianthome** [comment]
Hi Peter,

sure that is possible. The Ast nodes (https://github.com/julianthome/inmemantlr/blob/master/inmemantlr-api/src/main/java/org/snt/inmemantlr/tree/AstNode.java) carry the information about the rules. I have created an additional method (toDot) to the AstSerializer class that generates the "rule-tree" in dot format (https://github.com/julianthome/inmemantlr/blob/master/inmemantlr-api/src/main/java/org/snt/inmemantlr/tree/AstSerializer.java). 

Best wishes and kind regards,
  Julian

**Comment by mcheung63** [comment]
This code causes "java.lang.IllegalArgumentException: parserName must not be empty", any hints?

```
			File f = new File("/Users/peter/Desktop/HelloBase.g4");
			GenericParser gp = new GenericParser(f);
			DefaultTreeListener dlist = new DefaultTreeListener();

			gp.setListener(dlist);
			gp.compile();
			Ast ast = dlist.getAst();
			System.out.println(ast.toDot());
```

**Comment by mcheung63** [comment]
Even added "gp.setParserName("something");", still failed

**Comment by mcheung63** [comment]
ok, i finally found out this g4 file will cause error:

```
lexer grammar TestBaseLexer;

tokens  { Name }

// Default "mode": Everything OUTSIDE of a tag
Comment     :  '<!--' .*? '-->' ;
CDSect      :  '<![CDATA[' .*? ']]>' ;

fragment
Whitespace  :  ' ' | '\n' | '\t' | '\r' ;

fragment
Hexdigit    :  [a-fA-F0-9] ;

fragment
Digit       :  [0-9] ;
```

**Comment by julianthome** [comment]
Hello Peter,
The Antlr errors are propagated through the `ParsingException` exception (there is an example in the `TestMalformed` JUnit test case. Can I consider this issue as being closed? 
Best whishes and kind regards,
  Julian

**Comment by mcheung63** [comment]
Thanks a lot
