### ISSUE TITLE
Error when using with spring boot and antlr4

### ISSUE THREAD

**Issue by jdvr** [julianthome/inmemantlr#18]
I am working a project to general runtime grammars for parse email and I am getting this when trying to parse my files:

```
153. ERROR in /PisosGrammarParser.java (at line 1724)
	_decisionToDFA[i] = new DFA(_ATN.getDecisionState(i), i);
	                                                     ^^^^
ATN cannot be resolved to a type
----------
----------
154. ERROR in /PisosGrammarListener.java (at line 2)
	import org.antlr.v4.runtime.tree.ParseTreeListener;
        ^^^^^^^^^
The import org.antlr cannot be resolved
```
I generate a spring boot jar with spring boot maven plugin.

Do you have any idea about this issue?

Thanks!

**Comment by julianthome** [comment]
Hi Juan,

would it be possible for you to share your `pom.xml`. I would like to reproduce the problem.

Best, 
  Julian

**Comment by jdvr** [comment]
I have a project with two modules the spring app which poms looks like this:
```xml
        <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.tomcat</groupId>
					<artifactId>tomcat-jdbc</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>slf4j-log4j12</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>${kafka.version}</version>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
		</dependency>
	</dependencies>
```

The above project includes another one where I have all my antlr logic with this pom:

```xml
<dependencies>
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4</artifactId>
            <version>${antlr.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.julianthome</groupId>
            <artifactId>inmemantlr-api</artifactId>
            <version>1.3.3</version>
        </dependency>
</dependencies>
```

Everything is package using [spring boot mvn plugin as a jar](https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/maven-plugin/) with this configuration:

```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<version>${spring.boot.version}</version>
	<executions>
	  <execution>
		<goals>
		   <goal>repackage</goal>
		</goals>
	</execution>
	</executions>
</plugin>
```

I hope this helps you to understand what is happening.

Thanks.

**Comment by julianthome** [comment]
Hello Juan,

unfortunately, I was not able to reproduce the problem.

Could you switch to the most recent version `1.3.9` and see if it works. Please note that the `Ast` data structure has been renamed to `ParseTree`. 

The variable `antlr.version` should be set to 4.7 then. If it still does not work, would it be possible for you to isolate the problem by creating a small dummy project with just the (relevant) set of dependencies which yields the problem which you stated above?  

Best,
  Julian

**Comment by jdvr** [comment]
Hello @julianthome  I have create a the simplest possible app with the same problem I described on the issue.

I have shared the project here: https://github.com/jdvr/inmemantlr-antlr-spring-boot

Could you please take a look into it and help me to figure out what is happening with the generated files?.

I have included instruction to reproduce the problem on the repository

**Comment by jdvr** [comment]
I think I have found the problem in the [compiler](https://github.com/eclipse/eclipse.jdt.core/blob/0d382918bfebba26ea850857dfeda65fbb391527/org.eclipse.jdt.compiler.tool/src/org/eclipse/jdt/internal/compiler/tool/EclipseFileManager.java#L326) the classpath is set based on current application classpath. This is a _expected problem_ when using `java -jar foo.jar` because `-classpath` option is ignore by _java_ command.

I have added `antlr-4.7-complete.jar` to classpath:
```java
String cp = Optional.ofNullable(System.getProperty("java.class.path"))
				.filter(String::isEmpty)
				.map(c -> c + ":")
				.orElse("");
System.setProperty("java.class.path", cp + "/absolute/path/to/antlr-4.7-complete.jar");
```

This is a valid workaround but it is very error prone to have a jar with an external jar dependence out of `WEB-INF/lib`

**Comment by julianthome** [comment]
Hi Juan,

might it help you if I add an extra option to set the classpath for the eclipse compiler explicitly?

Best wishes and kind regards, 
  Julian

**Comment by jdvr** [comment]
I have solved this adding a property on spring configuration, that expect a file with the classpath for the eclipse compiler.

The good thing about spring configuration is that you can set a value on the `application.yml` and then override it passing a cli argument.
