### ISSUE TITLE
Save parser

### ISSUE THREAD

**Issue by TobiasScholl** [julianthome/inmemantlr#2]
It would be nice to have a feature which allows one to save a GenericParser on disk after using its compile method so one does not have to compile a specific grammar every time the software starts. I tried ObjectOutputStream which was expected to fail at this task and it did. Do you have any suggestions?

Btw I am glad that you created this antlr wrapper putting a parse result into a real tree and provided a working graphviz output (unlike antlr4).

**Comment by julianthome** [comment]
Dear Tobias,

thanks for the interest in inmemantlr. I've just added the serialization feature. However, I still have to add a couple of test cases before I can make a new release for maven central -- just to be sure that the serialization/deserialization works fine. 

Please let me know if you have other feature requests or if you find a bug ... I am always happy to take patches ;-).

Best wishes and kind regards,
  Julian
