### ISSUE TITLE
Generate and compile in memory only the lexer

### ISSUE THREAD

**Issue by ftomassetti** [julianthome/inmemantlr#23]
Is this supported? How can I do that?

**Comment by julianthome** [comment]
Hi Federico,
there is no interface for generating/compiling the lexer only, yet. I will add this functionality for the next release.
Thanks a lot and kind regards,
  Julian

**Comment by ftomassetti** [comment]
Thanks to you for this great piece of software!

**Comment by julianthome** [comment]
Hello @ftomassetti,
I did some changes to the `GenericParser` API so that it is possible to compile and use only the lexer (384ca3319e2a8dee43f72f367947e2fc1d9829ff) . Would the interface `public List<Token> lex(String toParse)` be suffient for your use case?
Best wishes and kind regards,
  Julian

**Comment by julianthome** [comment]
You can find the related test case under https://github.com/julianthome/inmemantlr/blob/2624c0cfd8276392dea1a50556f813152c33cc3b/inmemantlr-api/src/test/java/TestLexerGrammar.java

**Comment by ftomassetti** [comment]
Great, thanks for your work!
