### ISSUE TITLE
Can't load any v4 grammars

### ISSUE THREAD

**Issue by m-manseer** [julianthome/inmemantlr#34]
Sticking to your sample code in the [readme](https://github.com/julianthome/inmemantlr/blob/master/README.md), I can't get any of the [grammars-v4](https://github.com/antlr/grammars-v4) to work. When initializing GenericParser with [java8.g4](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4), for instance, it says:

```error(50): :1426:3: syntax error: 'lL' came as a complete surprise to me while matching a lexer rule
error(50): :1448:3: syntax error: '1-9' came as a complete surprise to me while matching a lexer rule
error(50): :1469:7: syntax error: 'xX' came as a complete surprise to me while looking for lexer rule element
error(50): :1479:3: syntax error: '0-9a-fA-F' came as a complete surprise to me while matching a lexer rule
error(50): :1505:3: syntax error: '0-7' came as a complete surprise to me while matching a lexer rule
error(50): :1521:7: syntax error: 'bB' came as a complete surprise to me while looking for lexer rule element
error(50): :1531:3: syntax error: '01' came as a complete surprise to me while matching a lexer rule
error(50): :1567:3: syntax error: 'eE' came as a complete surprise to me while matching a lexer rule
error(50): :1577:3: syntax error: '+-' came as a complete surprise to me while matching a lexer rule
error(50): :1582:3: syntax error: 'fFdD' came as a complete surprise to me while matching a lexer rule
error(50): :1593:7: syntax error: 'xX' came as a complete surprise to me while looking for lexer rule element
error(50): :1603:3: syntax error: 'pP' came as a complete surprise to me while matching a lexer rule
error(50): :1622:4: syntax error: ''\\\r\n]\n\t;\n\n// §3.10.5 String Literals\n\nStringLiteral\n\t:\t'"' StringCharacters? '"'\n\t;\n\nfragment\nStringCharacters\n\t:\tStringCharacter+\n\t;\n\nfragment\nStringCharacter\n\t:\t~["\\\r\n]\n\t|\tEscapeSequence\n\t;\n\n// §3.10.6 Escape Sequences for Character and String Literals\n\nfragment\nEscapeSequence\n\t:\t'\\' [btnfr"'\\' came as a complete surprise to me while looking for lexer rule element
error(50): :1660:3: syntax error: '0-3' came as a complete surprise to me while matching a lexer rule
error(50): :1735:3: syntax error: 'a-zA-Z$_' came as a complete surprise to me while matching a lexer rule
error(50): :1737:3: syntax error: '\u0000-\u007F\uD800-\uDBFF' came as a complete surprise to me while looking for lexer rule element
error(50): :1740:2: syntax error: '\uD800-\uDBFF' came as a complete surprise to me while matching a lexer rule
error(50): :1746:3: syntax error: 'a-zA-Z0-9$_' came as a complete surprise to me while matching a lexer rule
error(50): :1748:3: syntax error: '\u0000-\u007F\uD800-\uDBFF' came as a complete surprise to me while looking for lexer rule element
error(50): :1751:2: syntax error: '\uD800-\uDBFF' came as a complete surprise to me while matching a lexer rule
error(50): :1766:7: syntax error: ' \t\r\n\u000C' came as a complete surprise to me while matching a lexer rule
error(50): :1774:14: syntax error: '\r\n' came as a complete surprise to me while looking for lexer rule element
```

The line producing the output above is simply:

```this.parser = new GenericParser(grammarFile);```

where `grammarFile` is the [java8.g4](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4) file.

Ignoring the messages above and going on with the following:

```
this.parser.setListener(new ParserListener());
this.parser.compile();
```

fails with this exception:

```
 org.snt.inmemantlr.exceptions.CompilationException: No string code pipeline availabe
	at org.snt.inmemantlr.GenericParser.compile(GenericParser.java:313)
```

Using [version 1.4 of inmemantlr](https://mvnrepository.com/artifact/com.github.julianthome/inmemantlr/1.4) (for compatibility with Java 8). Any pointers are appreciated.

**Comment by julianthome** [comment]
Hi @m-manseer,

Please  make sure that you either pass the `.g4` file as a `File` or the content of the `.g4` file as String to the `GenericParser` interface (*not* the path as String). The following example should work with inmenantlr 1.4 (+Java 1.8).

    public static void main(String [] args) {


        File f = new File("/tmp/Java8.g4");
        GenericParser gp = null;
        try {
            gp = new GenericParser(f);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }


        DefaultTreeListener dt = new DefaultTreeListener();
        String s = FileUtils.loadFileContent("/tmp/HelloWorld.java");
        gp.setListener(dt);

        try {
            gp.compile();
        } catch (CompilationException e) {
            e.printStackTrace();
        }

        try {
            gp.parse(s, "compilationUnit",
                    GenericParser.CaseSensitiveType.NONE);
        } catch (IllegalWorkflowException e) {
            e.printStackTrace();
        } catch (ParsingException e) {
            e.printStackTrace();
        }

        System.out.println(dt.getParseTree().toDot());

    }

**Comment by m-manseer** [comment]
Thank you for looking into it, @julianthome. I have executed your code and this is its output:

```
error(50): :1426:3: syntax error: 'lL' came as a complete surprise to me while matching a lexer rule
error(50): :1448:3: syntax error: '1-9' came as a complete surprise to me while matching a lexer rule
error(50): :1469:7: syntax error: 'xX' came as a complete surprise to me while looking for lexer rule element
error(50): :1479:3: syntax error: '0-9a-fA-F' came as a complete surprise to me while matching a lexer rule
error(50): :1505:3: syntax error: '0-7' came as a complete surprise to me while matching a lexer rule
error(50): :1521:7: syntax error: 'bB' came as a complete surprise to me while looking for lexer rule element
error(50): :1531:3: syntax error: '01' came as a complete surprise to me while matching a lexer rule
error(50): :1567:3: syntax error: 'eE' came as a complete surprise to me while matching a lexer rule
error(50): :1577:3: syntax error: '+-' came as a complete surprise to me while matching a lexer rule
error(50): :1582:3: syntax error: 'fFdD' came as a complete surprise to me while matching a lexer rule
error(50): :1593:7: syntax error: 'xX' came as a complete surprise to me while looking for lexer rule element
error(50): :1603:3: syntax error: 'pP' came as a complete surprise to me while matching a lexer rule
error(50): :1622:4: syntax error: ''\\\r\n]\n\t;\n\n// §3.10.5 String Literals\n\nStringLiteral\n\t:\t'"' StringCharacters? '"'\n\t;\n\nfragment\nStringCharacters\n\t:\tStringCharacter+\n\t;\n\nfragment\nStringCharacter\n\t:\t~["\\\r\n]\n\t|\tEscapeSequence\n\t;\n\n// §3.10.6 Escape Sequences for Character and String Literals\n\nfragment\nEscapeSequence\n\t:\t'\\' [btnfr"'\\' came as a complete surprise to me while looking for lexer rule element
error(50): :1660:3: syntax error: '0-3' came as a complete surprise to me while matching a lexer rule
error(50): :1735:3: syntax error: 'a-zA-Z$_' came as a complete surprise to me while matching a lexer rule
error(50): :1737:3: syntax error: '\u0000-\u007F\uD800-\uDBFF' came as a complete surprise to me while looking for lexer rule element
error(50): :1740:2: syntax error: '\uD800-\uDBFF' came as a complete surprise to me while matching a lexer rule
error(50): :1746:3: syntax error: 'a-zA-Z0-9$_' came as a complete surprise to me while matching a lexer rule
error(50): :1748:3: syntax error: '\u0000-\u007F\uD800-\uDBFF' came as a complete surprise to me while looking for lexer rule element
error(50): :1751:2: syntax error: '\uD800-\uDBFF' came as a complete surprise to me while matching a lexer rule
error(50): :1766:7: syntax error: ' \t\r\n\u000C' came as a complete surprise to me while matching a lexer rule
error(50): :1774:14: syntax error: '\r\n' came as a complete surprise to me while looking for lexer rule element
org.snt.inmemantlr.exceptions.CompilationException: No string code pipeline availabe
	at org.snt.inmemantlr.GenericParser.compile(GenericParser.java:313)
	[...]
org.snt.inmemantlr.exceptions.IllegalWorkflowException: No antlr objects have been compiled or loaded
	at org.snt.inmemantlr.GenericParser.parse(GenericParser.java:459)
	[...]
graph {
	node [fontname=Helvetica,fontsize=11];
	edge [fontname=Helvetica,fontsize=10];
	n0 [label="root",shape=ellipse];
}
```

If that code runs on your machine without issues, there must be an environment-based problem. My project is built using Java 1.8.0_45 by Eclipse Photon on macOS. This is my maven dependency:

```
<dependency>
    <groupId>com.github.julianthome</groupId>
    <artifactId>inmemantlr-api</artifactId>
    <version>1.4</version>
</dependency>
```

At this stage I have managed to compile the grammars I need manually using the [ANTLR jar](http://www.antlr.org/download.html) file. By the looks of it I will probably no longer use inmemantlr, but will gladly help you fix the problem by providing any more information you need.

**Comment by julianthome** [comment]
Hi @m-manseer,

thanks a lot. I am using macOS, too. I will try to reproduce this issue using Eclipse Photon. I suppose you have used https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4?

Thanks again an kind regards,
  Julian

**Comment by m-manseer** [comment]
Yes, that's the correct grammar.

**Comment by julianthome** [comment]
Hi @m-manseer,
I could not reproduce the error with Eclipse Photon + Java 1.8. I put the `Java8.g4` and `HelloWorld.java`(https://github.com/julianthome/inmemantlr/blob/master/inmemantlr-api/src/test/resources/inmemantlr/HelloWorld.java) under `/tmp`. 

 I attached a screenshot down below. My `pom.xml` looks as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.julianthome</groupId>
    <artifactId>playground</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <java.version.source>1.8</java.version.source>
        <java.version.target>1.8</java.version.target>
    </properties>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.github.julianthome</groupId>
            <artifactId>inmemantlr-api</artifactId>
            <version>1.4</version>
        </dependency>
    </dependencies>
</project>
```


<img width="762" alt="grafik" src="https://user-images.githubusercontent.com/5645429/44145464-fc11ff40-a08b-11e8-86ad-f55b6d983ea4.png">

**Comment by m-manseer** [comment]
It's the strangest thing. I have started a blank Java/Maven project in Eclipse, pasted your .pom contents and my initial test code, ran it and it worked!

The same code within the project I want to incorporate `inmemantlr` in fails with above exceptions. I've also checked all the dependency versions and nothing seems to be replaced due to conflicting version numbers:

![screen shot 2018-08-16 at 15 50 38](https://user-images.githubusercontent.com/34419659/44212861-c3e67380-a16c-11e8-9387-45489bbc2290.png)

Same dependencies, same code, same grammars, same test files, different outcome. Should I discover the root cause I will post it here, but rest assured that this has nothing to do with your work. It must be an issue with my project setup. Sorry for the trouble and thanks for your help.

**Comment by julianthome** [comment]
Hi @m-manseer,

thanks a lot for checking. That is an interesting problem. Maybe there is a dependency in your project that includes an older version of `antlr`? Would it be possible for you to share your `pom.xml` file?

Thank you very much again for helping me to debug this issue.

Best wishes and kind regards,
  Julian

**Comment by m-manseer** [comment]
I've already checked that. Unfortunately I can't post the complete `.pom` publicly, but the screenshot above shows that `antlr 4.7.1` is included (exactly the version that `inmemantlr` requires).

**Comment by julianthome** [comment]
I am just asking because in the screenshot above it says "omitted for conflict with 4.7.1":
![grafik](https://user-images.githubusercontent.com/5645429/44395568-90279700-a53a-11e8-8415-05b18b8e3cbb.png)

Maybe it helps to change the order of your maven dependencies. Just for fun, could you try to put it right at the beginning (1st dependency) in your `pom.xml`. 

Thanks again @m-manseer 
  Julian

**Comment by m-manseer** [comment]
Oh that's just Eclipse's funny way of indicating that the dependency already exists and hence is not imported again (being a duplicate). What is actually being used is the exact same artefact and version as when changing the order.

See also: [Why is Eclipse Maven saying dependencies of same version are conflicting?](https://stackoverflow.com/questions/32976795/why-is-eclipse-maven-saying-dependencies-of-same-version-are-conflicting)
