### ISSUE TITLE
I can not run all test case 

### ISSUE THREAD

**Issue by geektcp** [julianthome/inmemantlr#36]
My ENV:
IDEA 2016.2 (default junit4)
JDK 1.8

Question:
why use junit5 ? (org.junit.jupiter.api)
how to run these test case ? give me your develop env info.

**Comment by julianthome** [comment]
Hi @geektcp, 
inmemantlr requires Java 10 https://github.com/julianthome/inmemantlr/blob/14763555b7972f2c303ff0164e49b4e959e5a17c/pom.xml#L24. 

On my machine, I am using:
```
>> java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)
```
Travis is also configued to use `openjdk10` (https://github.com/julianthome/inmemantlr/blob/14763555b7972f2c303ff0164e49b4e959e5a17c/.travis.yml#L6)
![image](https://user-images.githubusercontent.com/5645429/58380048-4ded2380-7fac-11e9-8323-0933491aa2c0.png)

Junit 5 comes in as a dependency, so all you need is basically Java10 in conjunction with Maven as build tool. You  should be able to import `inmemantlr` as Maven project then into IntelliJ and/or Eclipse or any other Java IDE. 

Alternatively you can just run `mvn test` on the cmd and should be able to see the following result:

```
[INFO] Reactor Summary for com.github.julianthome:inmemantlr 1.6:
[INFO]
[INFO] com.github.julianthome:inmemantlr .................. SUCCESS [  0.126 s]
[INFO] inmemantlr-api ..................................... SUCCESS [03:11 min]
[INFO] inmemantlr-tool .................................... SUCCESS [  0.734 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:12 min
[INFO] Finished at: 2019-05-26T11:42:50+02:00
```

**Comment by julianthome** [comment]
Just closing this - please feel free to re-open in case any issue arises.
