### ISSUE TITLE
How to get all the nodes after filtering 

### ISSUE THREAD

**Issue by sanjayankali-coder** [julianthome/inmemantlr#37]
Dear Julian
Recently I applied filtering for CPP code to get only function body.. Can you please guide me how to generate all the descending nodes of function body.. I mean I m interested in getting all the nodes of function body till last level.. I tried  calling getNodes() method from DefaultTreelistner class. But it is creating error as java.util.List cannot be converted to ParseTreeNode.. Kindly help

**Comment by julianthome** [comment]
Hi @sanjayankali-coder. If you are looking for a specific node, I would suggest to filter on the list of `ParseTreeNode` instances  returned by invoking `getNodes()` on the `ParseTree` object. 

In your particular case, I would look for the name of the body grammar rule and filter out the specific parse tree nodes that correspond to the rule. After filtering them, you would be able to work with the child nodes. 

Just to provide a quick example, the code snippet below can be used to obtain a `classDeclaration` node of a java program and traverse all child nodes aferwards: 

```java
ParseTreeNode classDecls = parseTree.getNodes()
  .stream()
  .filter(n -> n.getRule().equals("classDeclaration"))
  .findFirst()
  .get();
classDecls.getChildren().forEach(c -> System.out.println(c.getLabel()));
```

Please let me know if this answers your question or if any further help is required.

**Comment by julianthome** [comment]
In case you would like to extract the subtree that is rooted by a certain element, you can also use the `getSubtrees` method of the `ParseTree` class. 

https://github.com/julianthome/inmemantlr/blob/a1f5dc1bdc17a9ff60f9b05c9ff28dcb012db261/inmemantlr-api/src/main/java/org/snt/inmemantlr/tree/ParseTree.java#L233

For example,  for extracting an entire `classDeclaration` subtree, you could do:

```
 ParseTree classDecl = parseTree
  .getSubtrees(n -> n.getRule().equals("classDeclaration"))
  .iterator().next();
```

**Comment by julianthome** [comment]
@sanjayankali-coder I just assign this issue back to you. In case my responses answer you questions, please go ahead and close this issue.

**Comment by sanjayankali-coder** [comment]
thank you for your response..
if classDeclaration is the rule for filtering then i need  to add all the subtrees of classDeclaration or all childrens of classDeclaration to the resulting parsetree. 
on your above suggestions I will work on and get back to you...

i look forward for the answers from you..

**Comment by sanjayankali-coder** [comment]
Dear Julian 
the most important question to you is i am finding it difficult to work with enterEveryRule() and exitEveryRule() methods of class  DefaultTreeListner .. kindly let me know what all modifications need to be done in reset() method, enterEveryRule() and exitEveryRule()   so that all the childrens of filtered nodes get added in the resulting parsetree..

**Comment by sanjayankali-coder** [comment]
> Hi @sanjayankali-coder. If you are looking for a specific node, I would suggest to filter on the list of `ParseTreeNode` instances returned by invoking `getNodes()` on the `ParseTree` object.
> 
> In your particular case, I would look for the name of the body grammar rule and filter out the specific parse tree nodes that correspond to the rule. After filtering them, you would be able to work with the child nodes.
> 
> Just to provide a quick example, the code snippet below can be used to obtain a `classDeclaration` node of a java program and traverse all child nodes aferwards:
> 
> ```java
> ParseTreeNode classDecls = parseTree.getNodes()
>   .stream()
>   .filter(n -> n.getRule().equals("classDeclaration"))
>   .findFirst()
>   .get();
> classDecls.getChildren().forEach(c -> System.out.println(c.getLabel()));
> ```
> 
> Please let me know if this answers your question or if any further help is required.

Dear Julian 
It is printing only the node name and text of classDeclaration.. I want to add all children of classDeclaration upto last level to that node.

**Comment by sanjayankali-coder** [comment]
Dear Julian
If I apply filter for node classDeclaration then DefaultTreelistner prints only one node  ie classDeclaration.. I want to see all the children of classDeclaration along with the classDeclaration..

**Comment by sanjayankali-coder** [comment]
The suggestions given by you are not working for my need..

**Comment by julianthome** [comment]
@sanjayankali-coder would it be possible for you to provide a minimal example for your particular problem. Maybe a small code snippet of the code you would like to parse and the output you are expecting to see?

**Comment by sanjayankali-coder** [comment]
Thank you very much Julian 

the below code worked for me.
ParseTree classDecl = parseTree
  .getSubtrees(n -> n.getRule().equals("classDeclaration"))
  .iterator().next();


I congratulate you and wish you all the best for your upcoming releases..

**Comment by julianthome** [comment]
Thanks a lot @sanjayankali-coder 👍  Please don't hesitate to create another issue if you any further problems.

**Comment by sanjayankali-coder** [comment]
sure thanks again..
