### ISSUE TITLE
Line and Column Error in ParseTreeNode

### ISSUE THREAD

**Issue by ghost** [julianthome/inmemantlr#41]
Class ParseTreeNode has methods getSidx() and getEidx(), but these methods are not sufficient.

There should also be methods getBeginLine(), getBeginCharPositionInLine(), genEndLine(), and getEndCharPositionInLine().

This way, we can quickly locate where the node is in the source parsed.  Useful for output detailed error messages.

**Comment by julianthome** [comment]
Thanks a lot @calogero81 -- your suggestion makes a lot of sense to me 👍🏼 
Would you mind opening an MR to include you suggestions into inmemantlr? That would be awesome!

**Comment by ghost** [comment]
I forked your repository and I will play with it, trying to make the needed changes.

**Comment by ghost** [comment]
I have the proposed changes ready in a branch of my forked repository.  Unfortunately, the semantics of the end line and end char position in line is unclear, so I settled for just the begin line and begin char position in line.

How would you like to proceed?

**Comment by julianthome** [comment]
That is awesome @calogero81. Thanks a lot. Could you create a PR against inmemantlr so that we can discuss the changes in more depth in the context of the PR?

**Comment by julianthome** [comment]
@calogero81 sorry for the late response. I will have a closer look at the PR this weekend. Thanks a lot again for this contribution.
