### ISSUE TITLE
class Version

### ISSUE THREAD

**Issue by shawnwbts** [julianthome/inmemantlr#44]
Hi Julian,
when I  use this tool, it displays as follows.
Error: (4, 26) java: Unable to access org.snt.inmemantlr.GenericParser
   Wrong class file: /E:/maven/maven_rep1/com/github/julianthome/inmemantlr-api/1.7.0/inmemantlr-api-1.7.0.jar!/org/snt/inmemantlr/GenericParser.class
     The class file has the wrong version 54.0, it should be 52.0
     Please delete the file or make sure that the file is in the correct classpath subdirectory.

**Comment by julianthome** [comment]
Hi @taylorgag this looks like an (in)compatibility issue. Could you provide some details about the Java/JVM version you have been using?

**Comment by julianthome** [comment]
This issue should be resolved with #45
