### ISSUE TITLE
Don't know where or how to ask

### ISSUE THREAD

**Issue by mrn-aglic** [julianthome/inmemantlr#7]
I suppose inmemantlr doesn't support the C# grammar provided at: https://github.com/antlr/grammars-v4

Is there a possibility to get an AST using inmemantlr from parsers generated by ANTLR4?

Thanks, and sorry for opening an issue for this. 

I tried to do this:

val file = Source.fromFile(src).mkString
val read = file //.getLines
val dtListener = new DefaultTreeListener()

val stream = new ANTLRInputStream(read)

val lexer = new CSharpLexer(stream)

val tokens = new CommonTokenStream(lexer)

val parser = new CSharpParser(tokens)

parser.addParseListener(dtListener)

val ast: Ast = dtListener.getAst

But doesn't seem to work.

**Comment by julianthome** [comment]
Hello,

For inmemantlr, the workflow differs a bit from what you have described above. One can provide the `.g4` file directly to the GenericParser which compiles and instantiates the Lexer and Parser. In the example above, you operate directly on the ANTLR objects.

In case you would like to generate a simple AST, you could have a look at the `parse()` method of the `GenericParser` class; the `ParseTreeWalker` class might be interesting too. 

However, it seems that the C# grammar to which you were referring to is broken: neither the execution of `mvn clean test` from within the above mentioned repository nor the attempt to generated Parser/Lexer directly with the `antlr4` command line tool worked for me.

In case you have further questions, do not hesitate to contact me via E-mail.

Thanks a lot and kind regards,
  Julian
